// ATENÇÃO: Ajuste todos os caminhos dos requires abaixo para refletir a nova localização dos assets.
// Exemplo: Se a pasta assets foi movida para src/assets, troque "../../assets/KitVelas.png" por "../../../assets/KitVelas.png"
// Faça isso para TODOS os requires deste arquivo.

const lista_produto = {
    itens: {
        titulo: "Nossos Produtos",
        lista: [
            // Velas Aromáticas
            {
                id: 1,
                nome: "Kit Velas Aromáticas",
                descricao: "Kit de velas aromáticas composto por verbena, figo, chá branco e vaniglia.",
                descricaoDetalhada: "Kit de velas aromáticas composto por verbena, figo, chá branco e vaniglia. Cada vela traz uma fragrância única com notas delicadas e envolventes. Perfeitas para criar atmosferas acolhedoras e sofisticadas, transforma espaços com aromas que combinam suavidade e elegância. Feitas com o estilo e personalidade de Hecho.",
                preco: 200.00,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/KitVelas.png"),
                slider: [
                    require("../../../assets/VelaVerbena.png"),
                    require("../../../assets/VelaVanglia.png"),
                    require("../../../assets/VelaFigo.png"),
                    require("../../../assets/VelaChaBranco.png"),
                ]
            },
            {
                id: 2,
                nome: "Vela Cristal",
                descricao: "Vela aromática feita à mão, com acabamento refinado e fragrância envolvente.",
                descricaoDetalhada: "Vela em pote de vidro cristal âmbar 250 ml, feita à mão com acabamento refinado e fragrância envolvente. Sua tonalidade quente e translúcida valoriza a iluminação da chama, criando um efeito visual aconchegante e sofisticado. Ideal para compor a decoração com charme e perfume suave. Finalizada com o toque artesanal da Hecho.",
                preco: 549.90,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/VelaCristal.png"),
            },
            {
                id: 3,
                nome: "Vela Essência de Chá Branco",
                descricao: "Vela aromática feita à mão, com fragrância de chá branco.",
                descricaoDetalhada: "Vela aromática de chá branco e camomila, feita à mão para criar um ambiente acolhedor e suave. A combinação dessas duas fragrâncias oferece uma experiência olfativa tranquila, com notas florais delicadas e um fundo leve e confortável. Ideal para momentos de pausa ou para perfumar o ambiente com discrição e leveza. Finalizada com o cuidado artesanal da Hecho.",
                preco: 549.90,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/VelaCamomila.png"),
            },
            {
                id: 4,
                nome: "Vela Lavanda",
                descricao: "Vela aromática feita à mão, com fragrância de lavanda.",
                descricaoDetalhada: "Vela aromática de lavanda, com fragrância floral suave que transmite tranquilidade e bem-estar. Produz uma queima limpa e prolongada, ideal para transformar o ambiente em um refúgio acolhedor. Seu tom delicado e aroma reconfortante a tornam perfeita tanto para o uso diário quanto para momentos especiais. Feita com cera vegetal e pavio de algodão, cada peça reflete o cuidado artesanal e o estilo único da Hecho.",
                preco: 549.90,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/VelaLavanda.png"),
            },
            {
                id: 5,
                nome: "Kit Fragrância Figo",
                descricao: "Kit fragrância figo, contém uma unidade de vela, home spray e aromatizante de ambiente.",
                descricaoDetalhada: "Com aroma frutado e envolvente, este kit reúne três itens essenciais: uma vela artesanal, um home spray e um aromatizante de ambiente com fragrância de figo. Perfeito para garantir que o aroma se espalhe por toda a casa, criando uma atmosfera contínua e acolhedora com o estilo único de Hecho.",
                preco: 250.00,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/KitFigo.png"),
                slider: [
                    require("../../../assets/VelaFigo.png"),
                    require("../../../assets/HomeSprayFigo.png"),
                    require("../../../assets/AromatizanteFigo.png"),
                ]
            },
            {
                id: 6,
                nome: "Kit Fragrância Lavanda",
                descricao: "Kit fragrância lavanda, contém uma unidade de vela, home spray e aromatizante de ambiente.",
                descricaoDetalhada: "Kit Fragrância Lavanda – Vela, Home Spray e Aromatizante de Ambiente com notas florais e calmantes, o kit lavanda traz uma vela artesanal, um home spray e um aromatizante de ambiente. Ideal para proporcionar bem-estar e leveza, mantendo a fragrância suave e relaxante da lavanda presente em toda os da casa com o toque Hecho.", 
                preco: 250.00,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/KitLavanda.png"),
                slider: [
                    require("../../../assets/VelaLavanda.png"),
                    require("../../../assets/homeSprayLavanda.png"),
                    require("../../../assets/AromatizanteLavanda.png"),
                ]
            },
            {
                id: 7,
                nome: "Kit Verbena",
                descricao: "Kit completo com vela aromática, aromatizante de ambiente e home spray.",
                descricaoDetalhada: "Kit completo com vela aromática, aromatizante de ambiente e home spray, todos com a delicada fragrância de verbena. A combinação perfeita para transformar qualquer ambiente, proporcionando uma sensação de frescor e tranquilidade. Ideal para criar uma atmosfera acolhedora e perfumada, com um toque exclusivo de Hecho.",
                preco: 250.00,
                categoria: "Velas Aromáticas",
                imagem: require("../../../assets/KitVerbena.png"),
                slider: [
                    require("../../../assets/VelaVerbena.png"),
                    require("../../../assets/HomeSprayVerbena.png"),
                    require("../../../assets/aromatizanteVerbena.png"),
                ]
            },
            // Aromatizantes & Home Spray
            {
                id: 8,
                nome: "Aromatizante de Chá Branco",
                descricao: "Aromatizante de ambiente com essência de chá branco.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de chá branco, volume de 250 ml. Com notas delicadas de margarida, a fragrância traz um toque fresco e suave, criando uma atmosfera serena e acolhedora. Ideal para compor quartos, salas, banheiros e espaços de relaxamento, proporcionando um ambiente suave, elegante e com a essência floral de Hecho.",
                preco: 98.99,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/AromatizanteMargarida.png"),
            },
            {
                id: 9,
                nome: "Aromatizante Lavanda",
                descricao: "Aromatizante de ambiente com essência de lavanda.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de lavanda, volume de 250 ml. Suas notas suaves e florais combinam lavanda fresca com toques herbais, criando uma atmosfera de leveza e tranquilidade. Ideal para compor quartos, banheiros, salas ou espaços de descanso, levando o frescor da lavanda e a essência natural de Hecho para o ambiente.",
                preco: 380.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/AromatizanteLavanda.png"),
            },
            {
                id: 10,
                nome: "Aromatizante Verbena",
                descricao: "Aromatizante de ambiente com essência de verbena.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de verbena, volume de 250 ml. Com notas cítricas e refrescantes, traz um toque energizante e leve ao ambiente. Ideal para salas, banheiros, cozinhas e espaços de convivência, criando uma atmosfera vibrante e revigorante com a essência natural de Hecho.",
                preco: 98.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/aromatizanteVerbena.png"),
            },
            {
                id: 11,
                nome: "Home Spray Alecrim",
                descricao: "Home spray com essência de alecrim.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de alecrim, volume de 250 ml. Com notas herbais frescas, proporciona uma atmosfera leve e agradável. Ideal para salas, escritórios, cozinhas e ambientes que pedem um toque natural e cheio de vida com a essência de Hecho.",
                preco: 98.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/homeSprayAlecrim.png"),
            },
            {
                id: 12,
                nome: "Home Spray Bambu",
                descricao: "Home spray com essência de bambu.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de bambu, volume de 250 ml. Suas notas frescas e naturais trazem uma sensação de tranquilidade e leveza. Ideal para compor ambientes como salas, banheiros e quartos, proporcionando um toque de frescor e o estilo exclusivo de Hecho.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/homeSprayBambu.png"),
            },
            {
                id: 13,
                nome: "Home Spray Chá Branco",
                descricao: "Home spray com essência de chá branco.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de chá branco e camomila, volume de 250 ml. Combinando a suavidade do chá branco com o toque calmante da camomila, esta fragrância oferece uma experiência relaxante e revitalizante. Perfeito para ambientes como quartos e salas de descanso, trazendo uma sensação de tranquilidade e a sofisticação única de Hecho.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/homeSprayMargarida.png"),
            },
            {
                id: 14,
                nome: "Home Spray Figo",
                descricao: "Home spray com essência de figo.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de figo, volume de 250 ml. Com notas doces e frutadas, cria uma atmosfera acolhedora e sofisticada. Ideal para compor salas, quartos e espaços de relaxamento, proporcionando um toque delicado e o estilo único de Hecho.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/HomeSprayFigo.png"),
            },
            {
                id: 15,
                nome: "Home Spray Lavanda",
                descricao: "Home spray com essência de lavanda.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de lavanda, volume de 250 ml. Com notas florais suaves e frescas, traz uma sensação de calma e serenidade. Ideal para compor quartos, salas e banheiros, proporcionando um ambiente tranquilo e o toque refinado de Hecho.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/homeSprayLavanda.png"),
            },
            {
                id: 16,
                nome: "Home Spray Vaniglia",
                descricao: "Home spray com essência de baunilha.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de vaniglia, volume de 250 ml. Com notas doces e envolventes de baunilha, cria uma atmosfera acolhedora e reconfortante. Ideal para compor salas, quartos e espaços de descanso, proporcionando uma sensação de calor e o toque irresistível de Hecho.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/HomeSprayVaniglia.png"),
            },
            {
                id: 17,
                nome: "Home Spray Verbena",
                descricao: "Home spray com essência de verbena.",
                descricaoDetalhada: "Aromatizante de ambiente com fragrância de verbena 250 ml. Com notas cítricas e florais, proporciona uma atmosfera fresca e acolhedora. Ideal para compor salas, escritórios e cozinhas, trazendo um toque de frescor e a essência única de Hecho ao seu espaço.",
                preco: 56.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/HomeSprayVerbena.png"),
            },
            {
                id: 18,
                nome: "Kit Aromatizante Refil",
                descricao: "Refil para aromatizador de ambiente com essências naturais.",
                descricaoDetalhada: "Quatro fragrâncias exclusivas para renovar seus ambientes com variedade e sofisticação. Bambu traz leveza verde, Jasmim entrega um floral delicado, Lavanda acalma com suavidade e Alecrim desperta frescor herbal. Ideal para manter sua casa sempre perfumada com a essência natural de Hecho.",
                preco: 380.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/KitAromatizanteRefil.png"),
            },
            {
                id: 19,
                nome: "Kit Refil Aromatizante",
                descricao: "Aromatizadores de ambiente com essências naturais – Verbena, Figo, Chá Branco e Vaniglia (4 x 250 ml).",
                descricaoDetalhada: "Quatro fragrâncias únicas para compor diferentes atmosferas em seus ambientes. Verbena traz um floral cítrico suave, Figo apresenta um aroma frutado envolvente, Chá Branco combina leveza e serenidade com notas de camomila, e Vaniglia oferece um toque adocicado e acolhedor. Uma seleção especial com a identidade natural e sensorial de Hecho.",
                preco: 339.90,
                categoria: "Aromatizantes & Home Spray",
                imagem: require("../../../assets/KitAromatizantes.png"),
            },
            // Decoração
            {
                id: 20,
                nome: "Almofada Flores Larga",
                descricao: "Almofada de crochê feita à mão, flores coloridas.",
                descricaoDetalhada: "Almofada única, feita 100% à mão em crochê com linha mista (80% algodão / 20% poliéster). Possui composição exclusiva de squares com flores em tons quentes, tornando a peça totalmente artesanal. Enchimento macio incluso e acabamento reforçado. Ideal para decorar ambientes acolhedores com um toque de Hecho.",
                preco: 120.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaCroche.png"),
            },
            {
                id: 21,
                nome: "Almofada Squares de Flores Largo",
                descricao: "Almofada de crochê feita à mão",
                descricaoDetalhada: "Almofada unitária de crochê com squares de flores largos e diversificados, feita 100% à mão com linha mista (80% algodão / 20% poliéster). Produzida com agulha maior, tem ponto mais aberto e leve, ideal para cobrir almofadas. Acompanha forro e enchimento macio. Composição em tons frios, acabamento reforçado e design artesanal, perfeita para dar um toque de Hecho ao seu ambiente.",
                preco: 130.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaCroche2.png"),
            },
            {
                id: 22,
                nome: "Almofada de Crochê Colorida",
                descricao: "Almofada de crochê feita à mão, com design exclusivo.",
                descricaoDetalhada: "Almofada única de crochê feita 100% à mão com linha 100% algodão. Com pontos fechados, a peça apresenta um acabamento firme e texturizado, proporcionando maior durabilidade e conforto. A almofada é preenchida com enchimento macio, perfeita para ambientes descontraídos e cheios de personalidade, trazendo o toque exclusivo de Hecho ao seu espaço.",
                preco: 110.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaCroche3.png"),
            },
            {
                id: 23,
                nome: "Almofada Design Girassol",
                descricao: "Almofada de crochê feita à mão, com design exclusivo.",
                descricaoDetalhada: "Almofada unitária de crochê, feita 100% à mão com linha 100% algodão. Design de girassol texturizado e suave ao toque. A peça possui forro e enchimento aconchegante, garantindo um acabamento impecável. Ideal para adicionar um toque de elegância e personalidade ao seu espaço, com o estilo exclusivo de Hecho.",
                preco: 140.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaCrocheFlor.png"),
            },
            {
                id: 24,
                nome: "Almofada Rede Macramê Larga",
                descricao: "Almofada de macramê feita à mão, com design exclusivo.",
                descricaoDetalhada: "Capa decorativa em macramê feita 100% à mão com fio grosso de algodão trançado. A peça estiliza a almofada com uma rede firme e detalhada, valorizando a decoração com textura e charme. Ideal para compor ambientes com o estilo exclusivo de Hecho.",
                preco: 150.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaMacrame.png"),
            },
            {
                id: 25,
                nome: "Almofada Rede Macramê",
                descricao: "Almofada de macramê feita à mão, com design exclusivo.",
                descricaoDetalhada: "Capa decorativa em macramê feita 100% à mão com cordão de algodão trançado de espessura média. Apresenta um design detalhado que valoriza a peça com textura e originalidade. Um toque elegante e criativo para compor seu ambiente com a identidade única de Hecho.",
                preco: 145.00,
                categoria: "Decoração",
                imagem: require("../../../assets/AlmofadaMacrame2.png"),
            },
            {
                id: 26,
                nome: "Suportes para Vasos",
                descricao: "Conjunto 4 suportes para vasos em macramê, feitos à mão.",
                descricaoDetalhada: "Conjunto com 4 suportes para vasos em macramê, confeccionados com fio grosso de algodão na cor branca, complementado por detalhes em tom terra alaranjada. Cada suporte é trançado à mão com atenção aos detalhes, criando um design exclusivo e acolhedor. Ideal para complementar a decoração, trazendo um toque criativo e charmoso para qualquer ambiente. Feito com a qualidade e personalidade únicas de Hecho.",
                preco: 200.00,
                categoria: "Decoração",
                imagem: require("../../../assets/MacrameSuporteVasos.png"),
            },
            {
                id: 27,
                nome: "Filtro dos Sonhos Mandala",
                descricao: "Filtro dos sonhos feito à mão, com design exclusivo.",
                descricaoDetalhada: "Filtro dos sonhos decorativo com mandala em espiral, feito 100% à mão com cordão verde musgo de alta resistência. A estrutura firme em aro metálico possui 50 cm de diâmetro, trazendo presença e elegância à peça. Um elemento artesanal que transforma espaços com charme e autenticidade, expressando a essência criativa de Hecho.",
                preco: 180.00,
                categoria: "Decoração",
                imagem: require("../../../assets/FiltroSonhos.png"),
            },
            {
                id: 28,
                nome: "Filtro dos Sonhos Raiz de Árvore",
                descricao: "Filtro dos sonhos feito à mão, com design exclusivo.",
                descricaoDetalhada: "Mandala espiral feita 100% à mão com estrutura de bambu e detalhes em cordão decorativo. Inspirada no formato orgânico de troncos de árvore que crescem a partir das raízes, a peça traz um movimento natural e elegante. Possui aro de 25 cm de diâmetro e acabamento artesanal, ideal para levar a natureza e o estilo autêntico de Hecho para a decoração do seu ambiente.",
                preco: 190.00,
                categoria: "Decoração",
                imagem: require("../../../assets/FiltroSonhosArvore.png"),
            },
            {
                id: 29,
                nome: "Kit Sousplat Crochê",
                descricao: "Kit 4 sousplat de crochê, feito à mão, com design exclusivo.",
                descricaoDetalhada: "feitos à mão, que exploram variações de cor dentro de uma mesma paleta. Cada peça apresenta um design acolhedor e criativo, proporcionando um toque único e encantador à mesa. Com 30 cm de diâmetro, são ideais para compor um ambiente charmoso e cheio de personalidade, trazendo calor e estilo à sua decoração. Feitos com o estilo exclusivo de Hecho.",
                preco: 180.00,
                categoria: "Decoração",
                imagem: require("../../../assets/KitSousplatCroche.png"),
            },
            {
                id: 30,
                nome: "Mandala Flor em Espiral",
                descricao: "Mandala feita à mão, com design exclusivo.",
                descricaoDetalhada: "Mandala de flor decorativa feita 100% à mão com cordão na cor creme. Possui estrutura em espiral com uma flor detalhada ao centro, trazendo textura suave e acabamento artesanal. Com 35 cm de diâmetro, é perfeita para adicionar charme e personalidade à decoração com o estilo exclusivo de Hecho.",
                preco: 170.00,
                categoria: "Decoração",
                imagem: require("../../../assets/FiltroSonhosBranco.png"),
            },
            {
                id: 31,
                nome: "Manta de Crochê Squares Coloridos",
                descricao: "Manta feita à mão em squares de crochê, combinando tons vibrantes e alegres.",
                descricaoDetalhada: "Manta de crochê feita à mão, composta por squares de flores em cores vibrantes e alternadas. Cada peça é cuidadosamente trabalhada, criando um design criativo e cheio de personalidade. A combinação de tons fortes traz um toque alegre e acolhedor ao ambiente, tornando-a perfeita para quem busca um estilo único e cheio de energia. Feita com a qualidade e personalidade exclusivas de Hecho.",
                preco: 320.00,
                categoria: "Decoração",
                imagem: require("../../../assets/MantaCroche2.png"),
            },
            {
                id: 32,
                nome: "Manta de Crochê com Squares Florais",
                descricao: "Manta feita à mão em squares de crochê, com delicados detalhes florais em cada peça.",
                descricaoDetalhada: "Manta feita à mão em squares de crochê, combinando tons suaves e pastéis, com delicados detalhes florais em cada peça. Cada square é cuidadosamente trabalhado, criando uma composição charmosa e aconchegante. Ideal para adicionar um toque acolhedor e colorido ao seu espaço, perfeita para quem busca um estilo criativo e único. Feita com a qualidade e personalidade exclusivas de Hecho.",
                preco: 300.00,
                categoria: "Decoração",
                imagem: require("../../../assets/MantaCroche.png"),
            },
            {
                id: 33,
                nome: "Painel de Macramê Branco e Bege",
                descricao: "Painel de macramê feito à mão, com design exclusivo.",
                descricaoDetalhada: "Painel de macramê feito à mão nas cores branca e bege, com base em tronco decorativo de 50 cm de comprimento e extensão vertical de 110 cm. O trançado detalhado e o caimento dos fios criam uma composição retangular marcante, que adiciona textura e acolhimento à decoração. Uma peça que transforma o ambiente com o charme artesanal da Hecho.",
                preco: 200.00,
                categoria: "Decoração",
                imagem: require("../../../assets/painelMacrame (1).png"),
            },
            {
                id: 34,
                nome: "Painel de Macramê Terra",
                descricao: "Painel de macramê feito à mão, com design exclusivo.",
                descricaoDetalhada: "Painel em macramê na cor terra, suspenso por um galho natural tratado de 30 cm. Os fios descem em caimento harmonioso até 60 cm, formando uma peça vertical marcante. O trançado artesanal cria textura e presença, ideal para levar acolhimento e estilo a paredes que pedem um toque autêntico. Uma criação feita com identidade e alma Hecho.",
                preco: 180.00,
                categoria: "Decoração",
                imagem: require("../../../assets/PainelMacrame.png"),
            },
            {
                id: 35,
                nome: "Sousplat Colorido Mandala",
                descricao: "Sousplat de crochê feito à mão, com design exclusivo.",
                descricaoDetalhada: "Sousplat em crochê com design de mandala, feito à mão em composição única e colorida. A peça traz formas circulares em harmonia de tons, criando um visual criativo e acolhedor à mesa. Medindo cerca de 35 cm de diâmetro. Um toque de personalidade feito por Hecho.",
                preco: 90.00,
                categoria: "Decoração",
                imagem: require("../../../assets/sousplatColorido.png"),
            },
            {
                id: 36,
                nome: "Sousplat Crochê",
                descricao: "Sousplat de crochê feito à mão, com design exclusivo.",
                descricaoDetalhada: "Sousplat em crochê com borda desfiada, feito à mão com cuidado e atenção aos detalhes. Com 38 cm de diâmetro, é uma peça charmosa que traz textura e autenticidade à composição da mesa. Finalizado com a identidade única da Hecho.",
                preco: 85.00,
                categoria: "Decoração",
                imagem: require("../../../assets/sousplatCroche.png"),
            },
            {
                id: 37,
                nome: "Sousplat Crochê Diagonal",
                descricao: "Sousplat de crochê feito à mão, com design exclusivo.",
                descricaoDetalhada: "Sousplat em crochê com acabamento em ponta pontiaguda, que adiciona movimento e destaque ao contorno da peça. Com 38 cm de diâmetro, é inteiramente feito à mão, trazendo uma presença charmosa e acolhedora à mesa. Uma criação que expressa o cuidado artesanal e o estilo singular da Hecho.",
                preco: 95.00,
                categoria: "Decoração",
                imagem: require("../../../assets/sousplatCroche2.png"),
            },
            // Louças
            {
                id: 38,
                nome: "Conjunto de Jantar Completo",
                descricao: "Conjunto de jantar completo, composto por prato de sobremesa, prato fundo e prato raso.",
                descricaoDetalhada: "Sousplat em crochê com acabamento em ponta pontiaguda, que adiciona movimento e destaque ao contorno da peça. Com 38 cm de diâmetro, é inteiramente feito à mão, trazendo uma presença charmosa e acolhedora à mesa. Uma criação que expressa o cuidado artesanal e o estilo singular da Hecho.",
                preco: 400.00,
                categoria: "Louças",
                imagem: require("../../../assets/KitPratos (1).png"),
            },
            {
                id: 39,
                nome: "Kit Kakuzara",
                descricao: "Kit Kakuzara, composto por 6 pratos.",
                descricaoDetalhada: "Kit Kakuzara com 6 louças coloridas, cada uma medindo 11 x 8 cm. As peças possuem estampas decoupadas exclusivas, formando um conjunto criativo e complementar, ideal para servir com elegância ou decorar com personalidade e estilo, com o toque exclusivo de Hecho.",
                preco: 280.00,
                categoria: "Louças",
                imagem: require("../../../assets/KitKakuzara.png"),
            },
            {
                id: 40,
                nome: "Kit Louça Decoupada Campo",
                descricao: "Composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e pires",
                descricaoDetalhada: "Kit Louça Decoupada Azul, composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e seu respectivo pires. As peças apresentam fundo branco com decoração em tons de azul, com flores delicadas que criam um visual clássico e leve. A xícara branca complementa o conjunto com sutileza, ideal para servir com estilo ou compor a mesa com um toque refinado. Uma composição com a assinatura estética de Hecho.",
                preco: 350.00,
                categoria: "Louças",
                imagem: require("../../../assets/KitLouçaCafe2.png"),
            },
            {
                id: 41,
                nome: "Kit Louça Decoupada Delicado",
                descricao: "Composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e pires",
                descricaoDetalhada: "Kit Louça Decoupada Delicado, composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e seu respectivo pires. As peças possuem base branca com um tom suave de creme e uma decoração delicada. A xícara rosa traz um toque suave e encantador ao conjunto, ideal para servir com charme ou decorar a mesa com um estilo delicado e único. Um conjunto que reflete o toque exclusivo e criativo de Hecho.",
                preco: 340.00,
                categoria: "Louças",
                imagem: require("../../../assets/KitLouçaCafe (1).png"),
            },
            {
                id: 42,
                nome: "Kit Louça Decoupada Vintage",
                descricao: "Composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e pires",
                descricaoDetalhada: "Kit Louça Decoupada Vintage, composto por um prato de jantar, um prato fundo, um prato de sobremesa, uma xícara e seu respectivo pires. As peças possuem base branca, com uma decoração delicada de flores brancas e folhas verdes. Cada item é único, mas todos se complementam, criando um conjunto harmônico e sofisticado, ideal para servir com elegância ou decorar a mesa com um toque vintage. Feito com o estilo exclusivo e personalidade de Hecho.",
                preco: 320.00,
                categoria: "Louças",
                imagem: require("../../../assets/KitLouça.png"),
            },
        ]
    }
};

export default lista_produto;
