import { StyleSheet } from 'react-native';

// Verde principal: #6A6332
// Verde claro para card: #e6e3d0
// Fundo padrão: #f9f4ef

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9f4ef", // fundo igual às outras telas
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 32,
  },
  cardContainer: {
    marginTop: 24,
    backgroundColor: "#e6e3d0", // novo tom verde claro no card
    padding: 22,
    alignSelf: 'center',
    width: '95%',
    borderRadius: 16,
    elevation: 3,
    shadowColor: "#6A6332",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    borderWidth: 1.5,
    borderColor: "#6A6332",
  },
  camera: {
    width: 220,
    height: 220,
    alignSelf: 'center',
    borderRadius: 110,
    marginTop: 16,
    marginBottom: 16,
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "#6A6332",
    backgroundColor: "#e6e3d0",
  },
  cameraContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent: "flex-end",
    alignItems: "flex-end",
    padding: 8,
  },
  cameraVirarBotao: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 6,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#6A6332",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: "#6A6332",
  },
  tituloPerfil: {
    fontSize: 26,
    color: "#6A6332",
    fontWeight: "bold",
    marginBottom: 10,
    marginTop: 10,
    letterSpacing: 1.2,
    textAlign: "center",
    textTransform: "uppercase",
    backgroundColor: "#e6e3d0",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 12,
    overflow: "hidden",
    elevation: 2,
    shadowColor: "#6A6332",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  text: {
    fontSize: 16,
    marginLeft: 6,
    color: "#6A6332",
    fontWeight: "bold",
    marginTop: 8,
    marginBottom: 2,
  },
  input: {
    width: '100%',
    marginBottom: 14,
    marginLeft: 0,
    fontSize: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#6A6332",
    padding: 10,
    backgroundColor: "#f9f4ef",
    color: "#333",
  },
  message: {
    textAlign: 'center',
    paddingBottom: 10,
    color: "#6A6332",
    fontSize: 16,
    fontWeight: "bold",
  },
  permissionButton: {
    backgroundColor: "#6A6332",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 16,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#6A6332",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 2,
  },
  permissionButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },
});

export default styles;
